[toolchain]

[features]
resolution = true
skip-lint = false

[programs."https://api.devnet.solana.com"]
cliff-vesting = "F1RHqKoZ8exesFaiip8qos6smpfiHv3AdUCpeJLWtK4C"
vesting = "6zwP3ZLNrv5jwksK8Eztt7tFt2WYKDqdo5FXQkWv5otc"
vesting-v2 = "6U1EhFyn2nFpNsxD5Rf6JU1eQeRgBPPv3aET6xZkoF5F"
vesting-v3 = "8oHzDjuFH8n2oihjqqAq2Bu4L1iUMxYjMUUBcSpgJMzo"

[programs.localnet]
rentfi = "6HD23Gh57Ezr3PJ2UmpcpiCqCE582VXe3jvpGqZXJwjv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = ["https://api.devnet.solana.com", "wss://api.devnet.solana.com/"]
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
