[toolchain]

[features]
resolution = true
skip-lint = false

[programs."https://api.devnet.solana.com"]
cliff-vesting = "F1RHqKoZ8exesFaiip8qos6smpfiHv3AdUCpeJLWtK4C"
rentfi-vesting = "Edb58tf9QWCJVoVYqppvYKrgueAxqR1nFFsNxhc7pNQv"
vesting = "6zwP3ZLNrv5jwksK8Eztt7tFt2WYKDqdo5FXQkWv5otc"
vesting-v1 = "FUig98Z7S6ypR69rF5yHYaWUN41Jvjm7Qnkid8fhDpB3"
vesting-v2 = "6U1EhFyn2nFpNsxD5Rf6JU1eQeRgBPPv3aET6xZkoF5F"
vesting-v3 = "8oHzDjuFH8n2oihjqqAq2Bu4L1iUMxYjMUUBcSpgJMzo"

[programs.localnet]
rentfi = "6HD23Gh57Ezr3PJ2UmpcpiCqCE582VXe3jvpGqZXJwjv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "~/.config/solana/deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
